default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "admin" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "smartvm" } %>
  host: <%= ENV.fetch("DB_HOST") { "db" } %>

development:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] || "postgres" %>  # Use the same database name as in podman-compose.yml

test:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] || "eshop_test" %>  # Use the same database name as in podman-compose.yml

production:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] %>
  host: <%= ENV["DB_HOST"] %>
