version: '3'

services:
  web:
    build: .
    ports:
      - "3002:3002"
    volumes:
      - .:/app
    networks:
      - podman
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - podman

volumes:
  postgres-data:

networks:
  podman:
    driver: bridge
