version: '1'
services:
  web:
    image: eshop-users_web:local
    ports:
      - "3002:3002"
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=smartvm
    networks:
      - podman_network
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: smartvm
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - podman_network

volumes:
  postgres-data:

networks:
  podman_network:
    driver: bridge
